### ISSUE TITLE
no event fire click on apply button

### ISSUE THREAD

**Issue by rgprahul** [nikhil-001mehta/angular-2-daterangepicker#12]
Please give me solution how to resolve it.I can not get the date range into my .ts file. when we use autoApply:true with daterangepickerOptions then it work. but i need it on apply click.

**Comment by nikhil-001mehta** [comment]
I have fixed the issue. Please take latest version of the module via npm. see the demo [here](http://run.plnkr.co/plunks/Bhp9s2GKQAVeb5UlBU4x/) keep our developer tool open to see that the event gets fired. Hope it helps. Please close the issue if it fixes the problem. Let me know if there are any other issues you are facing. Thank you for your support.

**Comment by rgprahul** [comment]
This works fine but how to implement the functionality of Today,Last day and all.

**Comment by nikhil-001mehta** [comment]
@rgprahul  Do you mean the predefined range feature? Currently only default ranges can be shown. The work to accept custom ranges from options object is in progress I will release one more version this week with said feature. Thanks.

**Comment by nikhil-001mehta** [comment]
@rgprahul  I have added one more option named 'preDefinedRanges' to define custom ranges. See the [plunker](http://plnkr.co/edit/BtKrOwY8nNLMIdAikubM?p=preview) to understand how to use it.

**Comment by rgprahul** [comment]
Thanks Dear.


for your support.👍👍

**Comment by nikhil-001mehta** [comment]
@francyrho11 yes this is a bug. Thanks for letting me know. Its fixed in version 1.1.29. Thanks for your support.
