### ISSUE TITLE
how to pass start and end date equal to null ,by default it capture today date in control

### ISSUE THREAD

**Issue by heenaMahajan** [nikhil-001mehta/angular-2-daterangepicker#15]
In angular-2-daterangepicker,we are not able to set date to null in control.Please let me know that how to set null date or default label in that control

**Comment by nikhil-001mehta** [comment]
Yes it is designed to select today by default if nothing is provided that is how the original daterangepicker is behaving as [here](http://www.daterangepicker.com/). What behaviour exactly you want? Do you mean that there should not be any range selected by default if nothing is provided?

**Comment by heenaMahajan** [comment]
Yes,In first time when we load the page nothing should be selected until we select the range

**Comment by nikhil-001mehta** [comment]
Thanks @heenaMahajan I will try to add an option to the daterangepicker-options class in order to fulfill your requirements and release a new version in upcoming week.

**Comment by nikhil-001mehta** [comment]
hi @heenaMahajan thanks for your feedback I have added one option named 'noDefaultRangeSelected' you can set it to true in order to get the behaviour you want to, And please close the issue if you are okay with it,

**Comment by nikhil-001mehta** [comment]
Closing issue assuming it is has fulfilled requirements
