### ISSUE TITLE
Preinstall installs devDependencies

### ISSUE THREAD

**Issue by james-criscuolo** [nikhil-001mehta/angular-2-daterangepicker#17]
Do I need that preinstall set if I don't plan on developing inside the library? I'd like to use it, but I don't want to install those extra libraries, or force my team to as well. This occurs when just doing a normal `npm install angular-2-daterangepicker`.

**Comment by nikhil-001mehta** [comment]
no that's right you do not need to install those. I did not realize I have left it there in scripts, I have removed it. Please take latest version. And thank you for pointing it out.

**Comment by james-criscuolo** [comment]
Next problem I hit seems to be another small change, that I believe only matters with webpack, but should be beneficial in general. The error reads:

```
Uncaught Error: moduleId should be a string in "DaterangepickerComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```
Angular-cli has an open issue about it: https://github.com/angular/angular-cli/issues/3576. I haven't looked into it deeply enough to determine if this is a fault of webpack or angular, but just adding `.toString()` to module.id in the components should fix it. It looks like the typescript -> javascript conversion adds this metadata automatically, so maybe manually including it in typescript would be the solution.

I did test, and editing in the `.toString()` to `daterangepicker-component.js` and `calendar-component.js` does fix this, and I am able to successfully load the daterangepicker at that point.

**Comment by nikhil-001mehta** [comment]
sure i wll remove the dependancy on it. webpack seems to give problem with it.

**Comment by nikhil-001mehta** [comment]
@james-criscuolo Closing the issue. Assuming your issue is solved.
