### ISSUE TITLE
small error

### ISSUE THREAD

**Issue by costel-petrescu** [nikhil-001mehta/angular-2-daterangepicker#18]
Hi.
Using your program, I faced a small error.
It's in calendar-component.ts: 67.
exactly, it's this.length.
An error is following:
ERROR TypeError: Cannot read property 'length' of undefined
please, how can i fix this error?

Thanks.

**Comment by nikhil-001mehta** [comment]
Sure I would like to help. But it is difficult for me to help you unless you post the element which you are using to render the daterangepicker i.e the HTML tag which you are using in your code 
e.g. <date-range-picker [fromDate]="'04/01/2017'" [toDate]="'04/02/2017'" [format]="'DD/MM/YYYY'" (datesSelected)="demo($event)"> </date-range-picker>

**Comment by costel-petrescu** [comment]
![error](https://cloud.githubusercontent.com/assets/26811178/25324754/3c48a7b0-28d0-11e7-9dc9-410e7c954a33.png)

I tried to do your words, but it didn't run.
Errors are forwards.

**Comment by nikhil-001mehta** [comment]
Can you please post your html code too? Not whole but related to this daterangepicker? As in your image it shows that it has error in calendar.ts file, none of the file in package has name calendar.ts. Hope you are using latest version of this package, if not tell me the version you are using.

**Comment by costel-petrescu** [comment]
ok.

[calendar.ts.txt](https://github.com/nikhil-001mehta/angular-2-daterangepicker/files/950750/calendar.ts.txt)
[daterangepicker.component.ts.txt](https://github.com/nikhil-001mehta/angular-2-daterangepicker/files/950757/daterangepicker.component.ts.txt)

And then, what's wrong in this code ?
`<input class="input-mini form-control" [ngModel]="fromDate | formatMomentDate: format" (blur)="formatFromDate($event)" type="text" name="daterangepicker_start" />`

**Comment by nikhil-001mehta** [comment]
There is nothing wrong with this code. you have posted. Probably you are using date-range-picker tag in wrong way in your html code. What I want to know is how you are consuming my code? Please post that code which you are writing which is not part of this package, and the code which will consume my code.

**Comment by costel-petrescu** [comment]
Well, I'm going to change the calendar in your code.
But it doesn't work well.
The problem is I don't understand what function is getWeeksNumber()?
Can you explain about it?
Thanks.

**Comment by nikhil-001mehta** [comment]
yes it first gets all week numbers considering 1st jan week as first. And then it gets dates in those weeks.
e.g. for jan 2017 week numbers are 1,2,3,4,5 and for feb 2017 are 5,6,7,8,9. But you still did not post your HTML which is actually responsible to trigger my code.

**Comment by costel-petrescu** [comment]
Sorry, I'm confused.
Can you explain about bellow in detail?
Exactly, about `indexOf`.
`getWeekNumbers(monthRange: any) {
        let weekNumbers = [];
        let indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };
        monthRange.by('days', function(moment) {
            let ref;
            if (weekNumbers.length < 6 && (ref = moment.week(), indexOf.call(weekNumbers, ref)) < 0) {
                return weekNumbers.push(moment.week());
            }
        });
        return weekNumbers;
    }
    getWeeksRange(weeks: any, year: any, month: any) {
        let weeksRange = [];

        for (let i = 0, len = weeks.length; i < len; i++) {
            let week = weeks[i];
            let firstWeekDay, lastWeekDay;
            if (i > 0 && week < weeks[i - 1]) {
                firstWeekDay = moment([year, month]).add(1, "year").week(week).day(0);
                lastWeekDay = moment([year, month]).add(1, "year").week(week).day(6);
            }
            else {
                firstWeekDay = moment([year, month]).week(week).day(0);
                lastWeekDay = moment([year, month]).week(week).day(6);
            }
            let weekRange = moment.range(firstWeekDay, lastWeekDay);
            weeksRange.push(weekRange);
        }
        return weeksRange;
    }`
