### ISSUE TITLE
Is it compatible with angular 4 application. 

### ISSUE THREAD

**Issue by 02harleen** [nikhil-001mehta/angular-2-daterangepicker#23]
Hi, I have worked one angular 4 application. I have check this date picker, but there is no mention in the document. Please tells us is it compatible with angular 4application.

**Comment by nikhil-001mehta** [comment]
@02harleen Yes you can see it in the plunker [here](https://run.plnkr.co/plunks/BtKrOwY8nNLMIdAikubM/) it is working with both angular 4 and 5 as you can see in the plunker config.js it is already working with latest angular versions.

**Comment by khylias** [comment]
Applications running on Angular 2 run on Angular 5, except for breaking changes.
However, yes it may be good to add it in the description. :)

**Comment by nikhil-001mehta** [comment]
@khylias sure I will add. Let me know if you have faced any issues running with angular 5.
I personally have not tried it with angular 5 but I am sure about angular 4.
