### ISSUE TITLE
SingleCalendar TypeError

### ISSUE THREAD

**Issue by MFava91** [nikhil-001mehta/angular-2-daterangepicker#28]
https://github.com/nikhil-001mehta/angular-2-daterangepicker/blob/bfecf06688f574503e8f60278b001dd8bb06c04f/daterangepicker-component.ts#L274-L275

If fromDate is undefined: `this.fromDate.format is not a function`.
Missing condition in if statement.

**Comment by nikhil-001mehta** [comment]
I am not able to understand the case you are talking about. If single calndar is true and if startDate is not supplied in options then I am setting it to current system date. Can you please give me more insights if I am missing something here.

**Comment by nikhil-001mehta** [comment]
@MFava91 got it. I will fix it in next version.

**Comment by nikhil-001mehta** [comment]
@MFava91 I have fixed it in v.1.1.37

**Comment by MFava91** [comment]
@nikhil-001mehta It seems to works like a charm. Good job 👍
