### ISSUE TITLE
Did not work with Angular 6 .

### ISSUE THREAD

**Issue by sapanjwani** [nikhil-001mehta/angular-2-daterangepicker#32]
Hi,

Thanks for such a good module but this seems not working with angular 6 . I'm unable to select dates until i give min date and max date into options. In all other scenarios dates in calendar are not clickable.

**Comment by nikhil-001mehta** [comment]
Can you please share your app or a plnkr. Because the module [the demo here](https://nikhil-001mehta.github.io/angular-2-daterangepicker/) is already running on latest angular package.

**Comment by nikhil-001mehta** [comment]
@sapanjwani  thanks a lot for pointing out the issue. I have fixed the issue in v.1.1.43. Let me know if you are facing any issues or if you have any suggestions.

**Comment by nikhil-001mehta** [comment]
you can see the commit history [here](https://github.com/nikhil-001mehta/angular-2-daterangepicker/commit/f5e20b5044875b6942575844fdc4749f34dee071) expecially changes in daterangepicker-component.ts. 

In later commits I have made time picker aware of min max date time. You can see the latest [demo](https://nikhil-001mehta.github.io/angular-2-daterangepicker/) to see the change just select lowest possible date and see the time picker after selecting the date
