### ISSUE TITLE
Better integrate with Material controls

### ISSUE THREAD

**Issue by serge-fabiano** [nikhil-001mehta/angular-2-daterangepicker#81]
**Is your feature request related to a problem? Please describe.**

The material theme is not matching yours:

![image](https://user-images.githubusercontent.com/25266945/197894592-5fc07d03-1dce-4d3f-8cb5-7221f9655eaa.png)

**Describe the solution you'd like**

By allowing `<mat-form-field>` around your control, material theming will be applied 
```
    <mat-form-field>
      <daterangepicker
        class="col-md-12 col-lg-12 form-control"
        [options]="daterangepickerOptions"
        (rangeSelected)="dateChanged($event)">
      </daterangepicker>
    </mat-form-field>
```
The code above generates the followwing error:

`mat-form-field must contain a MatFormFieldControl.`

Maybe because matInput directive is maybe not present.

**Describe alternatives you've considered**

Providing manually full HTML/CSS theming generated by Material

Let me know if I missed something.

**Comment by serge-fabiano** [comment]
Another way would be to provide a directive like this:

```
    <mat-form-field>
      <input daterangepicker
        class="col-md-12 col-lg-12 form-control"
        [options]="daterangepickerOptions"
        (rangeSelected)="dateChanged($event)">
      </input>
    </mat-form-field>
```

**Comment by serge-fabiano** [comment]
I used a workaround to display a material input field in the UI and link your date/time picker control with it by cheating with the CSS:

![image](https://user-images.githubusercontent.com/25266945/198815313-a7ecb04e-b38e-4a39-a487-c22a7b77cd11.png)

**Comment by technikhil314** [comment]
yeah CSS is kept open for that purpose. Apparently creating headless UI is not that streight forward in angular. I am thinking of creating a pure js headless version of datetimerangepicker so people can use any css and their brand theme to build UI.
