### ISSUE TITLE
Hide/Show the Clear button

### ISSUE THREAD

**Issue by serge-fabiano** [nikhil-001mehta/angular-2-daterangepicker#82]
**Is your feature request related to a problem? Please describe.**
In some cases, you don't want to allow the user to clear the date

**Describe the solution you'd like**
Have a new property to show/hide the Clear button (why not also the others)

**Comment by technikhil314** [comment]
@LucasBrazi06 can you elaborate the usecase please? While its easy to implement it clear is there for ease of use from user experience standpoint. you can make the input box required if you want user to always select some date range. Would like to understand more from you. Thanks.

**Comment by serge-fabiano** [comment]
My use case is that I use the date/time picker to provide date/time filters and I don't want the user to clear the date.
Why providing the Clear button when it's not allowed, this is confusing the user.

**Comment by technikhil314** [comment]
@LucasBrazi06 
Fair enough but apply and cancel buttons cant be shown/hidden the same way. If user wants to undo their operation cancel is still very much handy. and apply is anyways shown only if autoapply is false. 
I will try to publish another version with feature to show hide clear button

**Comment by serge-fabiano** [comment]
@technikhil314 Thanks a lot!
