### ISSUE TITLE
'module.id' is a number in WebPack

### ISSUE THREAD

**Issue by denlight** [nikhil-001mehta/angular-2-daterangepicker#9]
VM44162:865 Uncaught Error: moduleId should be a string in "DaterangepickerComponent". See https://goo.gl/wIDDiL for more information.

This is the error I get when I try to include your module. First I had to fix a Unexpected character '@'  error but after that got fixed I get the one above. According to what I was able to find online the problem is that WebPack spits out the number for module.id but Angular needs a string. I'm not sure what to do about it =)

**Comment by denlight** [comment]
To fix this issue I had to remove modul.id from both Calendar And daterangepicker components and update the way template is included:
`@Component({
    selector: 'date-range-picker',
    template: require('./daterangepicker-component.html')
})`

`@Component({
    selector: 'calendar',
	template: require('./calendar-component.html'),
})`

**Comment by nikhil-001mehta** [comment]
okay. @denlight thanks for the help. I will merge your PR soon.

**Comment by nikhil-001mehta** [comment]
Merged PR to fix issue

**Comment by manjitsingh91** [comment]
You haven't  merged your dev branch to master so we cannot get the latest ts files  where 'modul.id' is removed.Means when we try to install angular-2-daterangepicker in our new project then we have to again remove the  'modul.id' manually.
